version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Run main.py
          command: python main.py

  test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Run test.py
          command: python test.py

  deploy:
    docker:
      - image: cimg/python:3.11
    steps:
      - run:
          name: Deploy
          command: echo "practical done"

workflows:
  build_and_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - main
